version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package-lock.json"}}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package-lock.json"}}
      - run:
          name: "Run type-check & unit-tests"
          command: "npm run check"
      - run:
          name: "Post code coverage"
          command: ./node_modules/.bin/codecov
workflows:
  version: 2
  test:
    jobs:
      - test
