version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package-lock.json"}}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package-lock.json"}}
      - run: npm run check
      - run: ./node_modules/.bin/codecov
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package-lock.json"}}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package-lock.json"}}
      - run: ./script/deploy.sh

workflows:
  version: 2
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
